---
title: Low-Emissions Solutions
timezone: UTC
collections:
  event:
    title: Event
    output: true
    permalink: /:collection/:name
  speakers:
    title: People
    output: false
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: uploads
    output: true
defaults:
  -
    scope:
      path: "Event"
    values:
      layout: "default"
      People:


email:
description:
url:
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- ".vagrant"
- ".gitignore"
- README.md
port: 4000
host: 0.0.0.0
livereload: true
