---
title: Low-Emissions Solutions
timezone: UTC
collections:
  event:
    title: Event
    output: true
  solutions:
    title: Solutions
    output: false
  speakers:
    title: Speakers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
      path: ""
      type: "pages"
  values:
      layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: default
- scope:
    path: ''
    type: event
  values:
    layout: event
    theme:
    hashtag:
    logo-file:
    logo-vector-file:
    schedule-text:
    location-text:
    permalink: "/:collection/:name"
- scope:
    path: ''
    type: speakers
  values:
    layout: default
    title-and-organization:
    photo:
- scope:
    path: ''
    type: solutions
  values:
    layout: default
    short-text:
    url:
    image:
twitter_username: Low2No
twitter_hashtag: LESC
facebook_username: Low2No
permalink: pretty
email: info@lowemissions.solutions
description:
baseurl: ''
url: http://lowemissions.solutions
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- ".vagrant"
- ".gitignore"
- README.md
port: 4000
host: 0.0.0.0
livereload: true
