---
title: Low-Emissions Solutions
timezone: UTC
twitter_username: Low2No
facebook_username: Low2No
permalink: pretty
collections:
  event:
    title: Event
    output: true
  speakers:
    title: Speakers
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: uploads
    output: true
defaults:
- scope:
    path: ''
    type: event
    permalink: "/:collection/:name"
  values:
    layout: default
    Speakers:
- scope:
    path: ''
    type: speakers
    permalink: "/:collection/:name"
  values:
    layout: default
    title and organization:
    short bio text:
    photo:
email: info@lowemissions.solutions
description:
baseurl: ""
url: http://lowemissions.solutions
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- ".vagrant"
- ".gitignore"
- README.md
port: 4000
host: 0.0.0.0
livereload: true
