---
title: Low-Emissions Solutions
timezone: UTC
collections:
  event:
    title: Event
    output: true
  posts:
    title: Posts
    output: true
  solutions:
    title: Solutions
    output: false
  speakers:
    title: Speakers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: event
  values:
    layout: event
    Speakers:
    schedule text:
- scope:
    path: ''
    type: speakers
  values:
    layout: default
    title and organization:
    short bio text:
    photo:
- scope:
    path: ''
    type: solutions
  values:
    layout: default
    title:
    short text:
    url:
    image:
twitter_username: Low2No
facebook_username: Low2No
permalink: pretty
email: info@lowemissions.solutions
description:
baseurl: ''
url: http://lowemissions.solutions
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- ".vagrant"
- ".gitignore"
- README.md
port: 4000
host: 0.0.0.0
livereload: true
