---
title: Low-Emissions Solutions
timezone: UTC
collections:
  event:
    title: Event
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:year/:month/:day/:title"
    related-videos:
    - title: 
      url: 
      description: 
- scope:
    path: ''
    type: event
  values:
    layout: event
    theme: 
    hashtag: 
    is-featured: 
    logo-file: 
    logo-vector-file: 
    location-text: 
    event-date-text: 
    registration-url: 
    schedule-text: 
    related-media:
    - description: 
      image: 
    permalink: "/:collection/:name"
twitter_username: Low2No
twitter_hashtag: LESC
facebook_username: Low2No
permalink: pretty
email: info@lowemissions.solutions
description: 
baseurl: "/"
url: http://lowemissions.solutions
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- ".vagrant"
- ".gitignore"
- README.md
- ".sass-cache"
port: 4000
host: 0.0.0.0
